feat: add plugin framework structure and example
linuxdeepin/dde-shell pull request #1
Opened 2023-10-19 08:21 UTC by 18202781743

Add basic functions and an example.
  TODO: rename class name of those element, e.g: applet, containment
corona, which is plasma's element.

Issue: https://github.com/linuxdeepin/developer-center/issues/5810

2023-10-19 08:34 UTC, BLumia approved these changes

2023-10-19 08:34 UTC, BLumia commented on frame/pluginloader.cpp
> +        m_pluginDirs = buildinPackagePaths();
内建是 `builtin`

2023-10-19 08:39 UTC, wineee requested changes

2023-10-20 02:51 UTC, asterwyx requested changes

2023-10-20 02:51 UTC, asterwyx commented on debian/control
> +Description: <insert up to 60 chars description>
描述写一下

2023-10-20 02:56 UTC, FeiWang1119 commented on debian/rules
> +export QT_SELECT = qt5
qt6

2023-10-20 02:56 UTC, FeiWang1119 commented on example/applet-example-data/exampleapplet.cpp
> +
多空行

2023-10-20 02:56 UTC, FeiWang1119 commented on example/corona-example/examplecorona.h
> +    virtual ~ExampleCorona();
加个override

2023-10-20 02:56 UTC, FeiWang1119 commented on frame/dstypes.h
> +        LeftPositioned, /**< Positioned left */
= 0

2023-10-20 03:36 UTC, asterwyx requested changes

2023-10-20 03:36 UTC, asterwyx commented on debian/rules
> +export QT_SELECT = qt5
删除

2023-10-20 03:36 UTC, asterwyx commented on frame/corona.cpp
> +static Types::Position typePosition(const QString &p)
一定可以保证QString是下面这些取值嘛

2023-10-20 03:36 UTC, asterwyx commented on frame/dstypes.cpp
> +DS_END_NAMESPACE
文件末尾都没有空行

2023-10-20 03:36 UTC, asterwyx commented on frame/panelview.h
> +
多余的空行删掉

2023-10-20 03:36 UTC, asterwyx commented on frame/pluginloader.cpp
> +        result << QCoreApplication::applicationDirPath() + "/../packages";
能不能把路径正规化

2023-10-20 03:36 UTC, asterwyx commented on frame/pluginloader.cpp
> +        result <<  QCoreApplication::applicationDirPath() + "/../plugins";
这里也是一样的

2023-10-20 03:36 UTC, asterwyx commented on frame/pluginloader.cpp
> +    }
```suggestion
    static DPluginLoader g_instance;
```

2023-10-20 03:36 UTC, asterwyx commented on misc/DDEShellConfig.cmake.in
> +set(DDEShell_INCLUDE_DIR ${DDEShell_INCLUDE_DIRS})
新项目不应该做过多的兼容

2023-10-20 03:36 UTC, asterwyx commented on misc/DDEShellConfig.cmake.in
> +set(DDEShell_LIBRARIES DDEShell)
export出来的target还是搞一个命名空间吧，不然在写的时候会给别人一种错觉

2023-10-20 03:36 UTC, asterwyx commented on shell/main.cpp
> +    Dtk::Core::DLogManager::registerFileAppender();
加上registerJournalAppender

2023-10-20 03:45 UTC, asterwyx commented on frame/corona.cpp
> +static Types::Position typePosition(const QString &p)
可能得考虑一下默认值怎么设置

2023-10-20 04:08 UTC, 18202781743 commented on frame/dstypes.h
> +        LeftPositioned, /**< Positioned left */
默认是0

2023-10-20 04:10 UTC, 18202781743 commented on frame/corona.cpp
> +static Types::Position typePosition(const QString &p)
这个可以延迟，可能直接删除了，等layer-shell集成就可能直接用它定义的了，

2023-10-20 06:01 UTC, asterwyx approved these changes

2023-10-20 06:02 UTC, merged