refact: launching app by dde-am tool
linuxdeepin/dde-shell pull request #110
Opened 2024-03-25 11:45 UTC by 18202781743

Launching app by dde-am tools instead of calling dbus directly.

2024-03-25 11:46 UTC, 18202781743 commented
https://github.com/linuxdeepin/dde-application-manager/pull/178

2024-03-26 02:31 UTC, zccrs requested changes

2024-03-26 02:31 UTC, zccrs commented on panels/dock/taskmanager/desktopfileamparser.cpp
> +        qWarning() << "Failed to launch the application path:" << path << process.errorString();
这里的 errorString 应该是 QProcess 自身的吧，如果是 dde-am 的报错，应该通过这个读不出来

2024-03-29 10:23 UTC, BLumia approved these changes

2024-03-29 11:14 UTC, merged