fix: x11 preview show without content
linuxdeepin/dde-shell pull request #194
Opened 2024-04-15 06:36 UTC by tsic404

paint event get new preview content frequently make kwin a high cpu make a timer show preview 500ms later

log: as title

2024-04-17 07:07 UTC, wineee approved these changes

2024-04-17 09:45 UTC, zccrs requested changes

2024-04-17 09:45 UTC, zccrs commented on panels/dock/taskmanager/x11preview.cpp
> +        if(!reply.isValid()) {
`if (`

2024-04-17 09:45 UTC, zccrs commented on panels/dock/taskmanager/x11preview.cpp
> +            ::close(fd[0]);
fd[1]不需要处理吗

2024-04-17 09:45 UTC, zccrs commented on panels/dock/taskmanager/x11preview.cpp
> +        ::close(fd[0]);
fd[1]不需要处理吗

2024-04-17 09:52 UTC, tsic404 commented on panels/dock/taskmanager/x11preview.cpp
> +            ::close(fd[0]);
fd[1] 在call完dbus后就处理了

2024-04-17 09:52 UTC, tsic404 commented on panels/dock/taskmanager/x11preview.cpp
> +        ::close(fd[0]);
fd[1] 在call完dbus后就处理了

2024-04-19 06:50 UTC, zccrs approved these changes

2024-04-19 06:58 UTC, merged