fix: workspace item not preserving aspect ratio
linuxdeepin/dde-shell pull request #199
Opened 2024-04-16 02:28 UTC by justforlxz

set Image to preserve aspect ratio

Log:

2024-04-17 03:36 UTC, tsic404 approved these changes

2024-04-17 09:47 UTC, zccrs requested changes

2024-04-17 09:47 UTC, zccrs commented on panels/dock/workspaceitem/package/workspaceitem.qml
> +                fillMode: Image.PreserveAspectCrop
不应该用PreserveAspectFit吗

2024-04-19 01:39 UTC, zccrs approved these changes

2024-04-19 03:54 UTC, merged