fix: player icon not update
linuxdeepin/dde-shell pull request #205
Opened 2024-04-17 07:33 UTC by tsic404

log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7858

2024-04-17 07:45 UTC, wineee commented on panels/dock/tray/plugins/media/mediaplayermodel.h
> +    void MetadataChanged(QVariantMap value);
QVariantMap 不用 const reference 吗？

2024-04-17 09:19 UTC, zccrs requested changes

2024-04-17 09:19 UTC, zccrs commented on panels/dock/tray/plugins/media/mediaplayermodel.h
> +#include <qcontainerfwd.h>
直接 include QVariantMap

2024-04-17 09:19 UTC, zccrs commented on panels/dock/tray/plugins/media/mediaplayermodel.h
> +    void MetadataChanged(QVariantMap value);
这里无所谓，本质上也是隐式共享的

2024-04-18 02:36 UTC, zccrs approved these changes

2024-04-18 03:35 UTC, merged