fix: don't save the visibility
linuxdeepin/dde-shell pull request #215
Opened 2024-04-18 06:44 UTC by FeiWang1119

save the visibility of a plugin item by dconfig tool

Issue: https://github.com/linuxdeepin/developer-center/issues/7959

2024-04-18 08:29 UTC, 18202781743 commented on panels/dock/dockpanel.cpp
> +            if (auto list = proxy->appletList("org.deepin.ds.dock.clipboarditem"); !list.isEmpty()) {
这个可以直接放到dockdbusproxy里做, 另外可以直接从proxy::applet()获取applet,

2024-04-18 08:29 UTC, 18202781743 commented on panels/dock/dockpanel.h
> +    Q_PROPERTY(QVariantMap pluginsVisible READ pluginsVisible WRITE setPluginsVisible NOTIFY pluginsVisibleChanged FINAL)
这个不需要暴露, 直接在dockdbusproxy里调用settings,

2024-04-18 08:29 UTC, 18202781743 commented on panels/dock/docksettings.cpp
> +            } else if (keyPluginsVisible == key) {
直接掉setPluginVisible ?

2024-04-18 09:00 UTC, FeiWang1119 commented on panels/dock/dockpanel.cpp
> +            if (auto list = proxy->appletList("org.deepin.ds.dock.clipboarditem"); !list.isEmpty()) {
done

2024-04-18 09:04 UTC, FeiWang1119 commented on panels/dock/docksettings.cpp
> +            } else if (keyPluginsVisible == key) {
done

2024-04-18 11:14 UTC, 18202781743 commented on panels/dock/dockdbusproxy.cpp
> +        connect(DockSettings::instance(), &DockSettings::pluginsVisibleChanged, this, [this] (const QVariantMap &pluginsVisible) {
封装下吧,这两大段代码几乎是相同的,

2024-04-18 11:24 UTC, zccrs requested changes

2024-04-18 11:24 UTC, zccrs commented on panels/dock/dconfig/org.deepin.ds.dock.json
> +			"name": "Plugins_Visible",
这是给user看的内容吧，不应该带下划线了

2024-04-19 03:06 UTC, FeiWang1119 commented on panels/dock/dockdbusproxy.cpp
> +        connect(DockSettings::instance(), &DockSettings::pluginsVisibleChanged, this, [this] (const QVariantMap &pluginsVisible) {
done

2024-04-19 03:09 UTC, FeiWang1119 commented on panels/dock/dconfig/org.deepin.ds.dock.json
> +			"name": "Plugins_Visible",
done

2024-04-19 03:35 UTC, 18202781743 approved these changes

2024-04-19 06:51 UTC, zccrs approved these changes

2024-04-19 07:13 UTC, merged