fix: After logging out, the workspace icons are not displayed
linuxdeepin/dde-shell pull request #223
Opened 2024-04-19 05:19 UTC by robertkill

Implement a mechanism to delay and then retrieve the workspace when the workspace is 0.

log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8023

2024-04-19 06:48 UTC, zccrs requested changes

2024-04-19 06:48 UTC, zccrs commented on panels/dock/workspaceitem/xworkspaceworker.cpp
> +        startTimer(200);
不要用 timer，用 `QDBusConnectionInterface::isServiceRegistered` 判断 dbus 服务是否注册。用 `QDBusConnectionInterface::serviceRegistered` 信号进行刷新。

2024-04-22 09:45 UTC, robertkill commented on panels/dock/workspaceitem/xworkspaceworker.cpp
> +        startTimer(200);
使用kwin的dbus接口重新实现了下

2024-04-24 05:38 UTC, tsic404 approved these changes

2024-04-24 06:03 UTC, merged