fix: tooltip shown when drag dock
linuxdeepin/dde-shell pull request #288
Opened 2024-04-26 08:59 UTC by tsic404

previent hover event from dragMouseArea to app mouseArea

log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8287

2024-04-28 02:19 UTC, BLumia approved these changes

2024-04-28 03:03 UTC, asterwyx commented
> previent hover event from dragMouseArea to app mouseArea
> 
> log: as title issue: [linuxdeepin/developer-center#8287](https://github.com/linuxdeepin/developer-center/issues/8287)

prevent

2024-04-28 03:03 UTC, asterwyx requested changes
更正commit message。

2024-04-29 05:30 UTC, asterwyx approved these changes

2024-04-29 05:38 UTC, merged