fix: do not hardcode plugin install dir
linuxdeepin/dde-shell pull request #361
Opened 2024-05-14 13:10 UTC by hillwoodroc

Log: do not hardcode plugin install dir for openSUSE and fedora

2024-05-14 13:32 UTC, tsic404 commented
<img width="684" alt="image" src="https://github.com/linuxdeepin/dde-shell/assets/48748112/1da47ff3-5c50-4752-8b3d-437f2dc0a609">

这个会带上 `x86_64-linux-gnu` 导致插件都找不到

2024-05-14 14:39 UTC, hillwoodroc commented
> <img alt="image" width="684" src="https://private-user-images.githubusercontent.com/48748112/330450295-1da47ff3-5c50-4752-8b3d-437f2dc0a609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTc3OTUsIm5iZiI6MTcxNTY5NzQ5NSwicGF0aCI6Ii80ODc0ODExMi8zMzA0NTAyOTUtMWRhNDdmZjMtNWM1MC00NzUyLThiM2QtNDM3ZjJkYzBhNjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE0MzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNzNmZmE1Yjc0ZjhlODcwOTk4NjlhOTgxNGU2NDZiNDMyZTFjMzViZDI4ZWM2Mjc5NmEwZDhhMDUyMGRlMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bsvXhJ4fInCKjTZWdDo92KnAoKGtWIaWiOtJhiwrw18">
> 
> 这个会带上 `x86_64-linux-gnu` 导致插件都找不到 要改动的话，plugin path的查找路径都要修改。

单独给 debian  的 rule 文件定义一个路径是否可以？

2024-05-14 14:41 UTC, hillwoodroc commented
或者在 CMakeLists.txt 文件里面加一行 include(GNUInstallDirs) 如何？

2024-05-17 01:33 UTC, tsic404 commented
/test all

2024-05-17 13:03 UTC, hillwoodroc commented
我加了个条件判断，不会影响 debian 的安装目录了。

2024-05-17 14:14 UTC, hillwoodroc commented
又更新了一下，把 c++ 里面的死路径全部改为 QString 来获取的动态路径了。你们试试看又没有什么问题。

2024-05-22 02:30 UTC, tsic404 commented
/test all

2024-05-24 14:49 UTC, hillwoodroc commented
/test all

2024-06-03 07:35 UTC, wineee requested changes

2024-06-03 07:35 UTC, wineee commented on panels/dock/CMakeLists.txt
> +elseif(CMAKE_INSTALL_LIBDIR MATCHES "lib/*")
应该在 debian/rules 设置 -DPLUGIN_INSTALL_DIR ，最好不要在 cmake 做这些判断

2024-06-14 14:20 UTC, closed without merging