fix: dock item duplicated after drag and drop
linuxdeepin/dde-shell pull request #467
Opened 2024-06-24 07:39 UTC by kegechen

DelegateModel 数据和 model 中数据没有同步。
现在就算在其他区域松开也是会更新到 model

Issue: https://github.com/linuxdeepin/developer-center/issues/9345

2024-06-24 07:43 UTC, BLumia commented on panels/dock/taskmanager/package/TaskManager.qml
> -                    if (drop.keys.includes("text/x-dde-launcher-dnd-desktopId")) {
这不太对吧？这里是为了“从启动器拖拽固定到任务栏”的需求的逻辑。

2024-06-24 08:04 UTC, kegechen commented on panels/dock/taskmanager/package/TaskManager.qml
> -                    if (drop.keys.includes("text/x-dde-launcher-dnd-desktopId")) {
这个功能现在好像还没法用

2024-06-24 08:15 UTC, kegechen commented on panels/dock/taskmanager/package/TaskManager.qml
> -                    if (drop.keys.includes("text/x-dde-launcher-dnd-desktopId")) {
部队，全屏时可用

2024-06-25 09:30 UTC, asterwyx requested changes

2024-06-25 09:30 UTC, asterwyx commented on panels/dock/taskmanager/package/TaskManager.qml
> -                    taskmanager.Applet.dataModel.moveTo(drop.source.itemId, visualIndex)
onDrop可以直接去掉了

2024-06-25 09:30 UTC, asterwyx commented on panels/dock/taskmanager/package/TaskManager.qml
> +                        visualModel.model = taskmanager.Applet.dataModel
这个应该不需要，qml绑定会重新计算。

2024-06-25 09:31 UTC, tsic404 approved these changes

2024-06-25 09:51 UTC, tsic404 commented on panels/dock/taskmanager/package/TaskManager.qml
> -                    taskmanager.Applet.dataModel.moveTo(drop.source.itemId, visualIndex)
launchpad的drop还需要吧

2024-06-26 00:50 UTC, kegechen commented on panels/dock/taskmanager/package/TaskManager.qml
> +                        visualModel.model = taskmanager.Applet.dataModel
这行才是解决这个bug的关键，不更新就重复了

2024-06-26 06:22 UTC, asterwyx approved these changes

2024-06-26 06:46 UTC, merged