fix dock missing install qmlplugin
linuxdeepin/dde-shell pull request #48
Opened 2023-12-19 07:21 UTC by 18202781743

- fix: missing files for dock plugin
- chore: update changelog to 0.0.3

2023-12-19 07:22 UTC, 18202781743 commented
/integr-topic dde-shell-0.0.2

2023-12-19 07:52 UTC, wineee requested changes

2023-12-19 07:52 UTC, wineee commented on debian/changelog
> +dde-shell (0.0.3) unstable; urgency=medium
unreleased ?

2023-12-19 07:54 UTC, wineee approved these changes

2023-12-19 08:56 UTC, asterwyx approved these changes

2023-12-20 06:46 UTC, 18202781743 commented
/integr-topic dde-shell-0.0.2

2023-12-20 07:33 UTC, Zeno-sole commented
/integr-topic dde-shell-0.0.2

2023-12-21 07:40 UTC, merged