fix: modify panel popup shadow offset and color
linuxdeepin/dde-shell pull request #706
Opened 2024-08-15 06:03 UTC by yixinshark

as title

Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10325

2024-08-15 06:06 UTC, 18202781743 commented on frame/qml/PanelPopupWindow.qml
> +    D.DWindow.shadowColor: Qt.rgba(0, 0, 0, 0.4)
颜色需要区分暗亮主题么?

2024-08-15 07:29 UTC, yixinshark commented on frame/qml/PanelPopupWindow.qml
> +    D.DWindow.shadowColor: Qt.rgba(0, 0, 0, 0.4)
已询问设计，深色模式黑色50%透明度，浅色模式黑色40%的透明度。

2024-08-16 01:32 UTC, 18202781743 approved these changes

2024-08-16 02:03 UTC, 18202781743 commented on frame/qml/PanelPopupWindow.qml
> +    D.DWindow.shadowColor: DockPalette.panelPopupShadowColor
这样无法取到color, 应该先定义property, 再用D.ColorSelector 去获取D.Palette的颜色,

2024-08-16 02:03 UTC, 18202781743 requested changes
这样无法取到color, 应该先定义property, 再用D.ColorSelector 去获取D.Palette的颜色,

2024-08-20 08:03 UTC, yixinshark commented on frame/qml/PanelPopupWindow.qml
> +    D.DWindow.shadowColor: DockPalette.panelPopupShadowColor
已修改

2024-08-20 09:41 UTC, 18202781743 approved these changes

2024-08-20 09:47 UTC, 18202781743 approved these changes

2024-08-20 09:49 UTC, yixinshark commented
/forcemerge

2024-08-20 09:49 UTC, merged