fix: plugin theme not follow dock
linuxdeepin/dde-shell pull request #72
Opened 2024-01-15 02:26 UTC by tsic404

1. wayland compositor send event, need to specify the client to receive the message default client is null which will make assert invalid.
2. forward surface destory signal, and remove saved surface in DockCompositor

log: fix dock plugin theme not follow dock
issue: https://github.com/linuxdeepin/developer-center/issues/6879

2024-01-15 09:01 UTC, asterwyx requested changes

2024-01-15 09:23 UTC, tsic404 commented on panels/dock/dockplugin/protocol/dock-plugin-manager-v1.xml
之前的用不到了

2024-01-17 05:24 UTC, asterwyx approved these changes

2024-01-17 05:30 UTC, tsic404 commented
/merge

2024-01-17 05:30 UTC, merged