feat: add appruntimeitem plugin
linuxdeepin/dde-shell pull request #756
Opened 2024-09-16 06:13 UTC by wjyrich

Add a plugin to count application running time and manage application running.

Log: Add a plugin to count application running time and manage application running.

2024-09-18 02:45 UTC, asterwyx requested changes

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/CMakeLists.txt
> +    ../dockiteminfo.h
不要采用这种相对路径，使用${CMAKE_SOURCE_DIR}等内置变量拼接路径

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/CMakeLists.txt
> +    "../"
同上，不要使用相对路径。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/appruntimeitem.cpp
> +#include "../constants.h"
代码中也不要相对路径，将相应的目录添加到include_directories里面。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/appruntimeitem.cpp
> +            xcbThread = new XcbThread();
这个变量没有地方释放内存，下面的engine也是同理，使用asan检查一下这个项目的内存问题，确保内存不出问题。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/appruntimeitem.h
希望统计时间的功能可以作为taskmanager的扩展功能，而你这个插件单纯只是显示数据，这样这里就不需要重新打开xcb thread。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/appruntimeitem.h
目前的功能都是依赖X11实现，所以请做判断，在wayland环境下关闭该项功能。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/package/ShowRuntimeMenu.qml
> +            Text { text: "运行时长"; width: parent.width / 4 }
项目中已经有翻译，代码中就不应该出现中文，而是使用英文，然后将相应的文案翻译成中文。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/package/ShowRuntimeMenu.qml
> +                        text: name  // 使用模型角色
不应出现中文注释。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/package/icons/appruntime.svg
这个图标注意版权问题。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/windowmanager.cpp
> +void WindowManager::setWindowInfo_qiantai(const QString &name, uint id) {
- 驼峰命名规则和下划线命名风格在项目中不能混用，dde-shell采用驼峰命名。
- 在项目中不要使用拼音，替换成相应的英文：foreground（前台），background（后台）。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/windowmanager.cpp
> +        info.name = "前台应用："+name;
同理，代码中不能出现中文。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/windowmanager.h
> +struct WindowInfo_1 {
这个类名不符合规范，不要包括下划线。

2024-09-18 02:45 UTC, asterwyx commented on panels/dock/appruntimeitem/xcb_get.cpp
> +    emit windowDestroyed(e->window);
使用Q_EMIT和Q_SIGNALS等宏，而不要使用emit和signal等Qt定义的关键字。

2024-09-23 06:07 UTC, wjyrich commented on panels/dock/appruntimeitem/appruntimeitem.h
能否在CmakeList中添加BUILD_WITH_X11 的if判断条件，从而进行启动在X11运行此功能，在wayland环境下关闭该项功能。

2024-09-24 08:56 UTC, asterwyx requested changes

2024-09-24 08:56 UTC, asterwyx commented on panels/dock/appruntimeitem/xcbgetinfo.h
> +    void eventsLoop(void);
一般叫eventLoop

2024-09-24 08:56 UTC, asterwyx commented on panels/dock/appruntimeitem/xcbgetinfo.h
> +signals:
使用Q_SIGNALS等宏而不是关键字。

2024-09-27 08:53 UTC, tsic404 commented on panels/dock/appruntimeitem/appruntimeitem.h
> +private:
下面变量准守一下 m_ 开头的标准

2024-09-27 08:54 UTC, tsic404 commented on panels/dock/appruntimeitem/appruntimeitem.cpp
> +            engine = new QQmlApplicationEngine();
new 一个新的Engine ？

2024-09-30 01:23 UTC, wjyrich commented
/test

2024-10-12 09:58 UTC, asterwyx commented on panels/dock/appruntimeitem/appruntimeitem.h
不行，因为x11和wayland用的是同一次build,无法区分

2024-10-20 16:24 UTC, asterwyx commented on panels/dock/appruntimeitem/package/ShowRuntimeMenu.qml
> +            windowManager.setWindowInfoInActive(id, name);
既然这两个类的信号有那么强的关系，应该考虑在C++里面就将两个类联系起来，在qml中不应该有这样的逻辑，qml只负责渲染画面就可以了。

2024-10-20 16:30 UTC, asterwyx commented on panels/dock/appruntimeitem/translations/org.deepin.ds.dock.appruntimeitem.ts
> +        <source>app_runtime</source>
文案应该按照正常英文语句或者标题的格式书写，像这种应该是按照标题的格式。

2024-10-20 16:53 UTC, asterwyx commented on panels/dock/appruntimeitem/xcbgetinfo.h
> +    QList<xcb_window_t> m_allOpenedWindows;
```suggestion
    QList<xcb_window_t> m_allOpenWindows;
```
open本身是形容词。

2024-10-20 16:54 UTC, asterwyx commented on panels/dock/appruntimeitem/xcbgetinfo.h
> +} WindowInfo;
在C++中，因为struct可以不带关键字使用，我们很少使用这种typedef定义类型，直接像定义类一样定义，像类一样使用就可以了。

2024-10-20 16:55 UTC, asterwyx commented on panels/dock/appruntimeitem/xcbgetinfo.h
> +enum { INACTIVE, ACTIVE };
Qt中更倾向于将枚举放到某个类里面，并且使用Q_ENUM。

2024-10-22 03:00 UTC, asterwyx requested changes

2024-10-22 06:36 UTC, asterwyx commented on panels/dock/appruntimeitem/CMakeLists.txt
> +find_package(XCB REQUIRED)
使用IMPORTED_TARGET

2024-10-22 06:36 UTC, asterwyx commented on panels/dock/appruntimeitem/CMakeLists.txt
> +include_directories(${CMAKE_SOURCE_DIR}/panels/dock/taskmanager)
不要使用include_directories,使用target_include_directories

2024-10-24 03:43 UTC, wjyrich commented on panels/dock/appruntimeitem/appruntimeitem.cpp
> +#include "../constants.h"
由于ddetrayloader依赖提供了搜索头文件路径包括了usr/include/dde-dock，导致constants.h文件冲突

2024-10-28 05:48 UTC, tsic404 commented on panels/dock/appruntimeitem/package/appruntimeitem.qml
> +        onClicked: {
弹出的东西，可以考虑用PanelPopup，而不是自己加载一个ApplicationWindow的方式

2024-10-28 05:50 UTC, tsic404 commented on panels/dock/appruntimeitem/CMakeLists.txt
> +install(FILES "package/icons/appruntime.svg" DESTINATION share/dde-dock/icons/dcc-setting)
这个应该是 `${CMAKE_INSTALL_DATAROOTDIR}/dde-dock/icons/dcc-setting`

2024-10-28 07:28 UTC, wjyrich commented on panels/dock/appruntimeitem/package/appruntimeitem.qml
> +        onClicked: {
研究一下pannelPopup 后面重新提交PR修改

2024-10-29 14:33 UTC, asterwyx approved these changes

2024-10-30 03:04 UTC, asterwyx commented
/forcemerge

2024-10-30 03:05 UTC, merged