panel/dock/taskmanager/structuraloptimization
linuxdeepin/dde-shell pull request #87
Opened 2024-02-19 07:09 UTC by tsic404

2024-02-20 06:07 UTC, asterwyx requested changes

2024-02-20 06:07 UTC, asterwyx commented on panels/dock/taskmanager/appitem.cpp
> +QString AppItem::name()
怎么把const删掉了。

2024-02-21 03:23 UTC, tsic404 commented on panels/dock/taskmanager/abstractitem.h
> +    Q_PROPERTY(QString dockedDir READ dockedDir NOTIFY dockedDirChanged FINAL)
taskmanager 上的 抽象item， appitem, groupitem 和floderitem都是从它派生来的

2024-02-21 03:24 UTC, tsic404 commented on panels/dock/taskmanager/appitem.cpp
> +QString AppItem::name()
变成AbstractItem的override了

2024-02-21 05:55 UTC, asterwyx commented on panels/dock/taskmanager/abstractitem.h
> +    Q_PROPERTY(QString dockedDir READ dockedDir NOTIFY dockedDirChanged FINAL)
我的意思是这个dockedDir

2024-02-21 05:56 UTC, asterwyx commented on panels/dock/taskmanager/appitem.cpp
> +QString AppItem::name()
override和const也不冲突啊

2024-02-21 05:56 UTC, asterwyx commented on panels/dock/taskmanager/appitem.cpp
> +QString AppItem::name()
AbstractItem的定义本身就应该是const的

2024-02-26 09:39 UTC, tsic404 commented on panels/dock/taskmanager/abstractitem.h
> +    Q_PROPERTY(QString dockedDir READ dockedDir NOTIFY dockedDirChanged FINAL)
因为是抽象类型，所以把所有的属性都附加过来了，包含要固定的文件路径，要固定分组的desktop id和运行时产生的窗口id

2024-02-27 02:15 UTC, asterwyx approved these changes

2024-02-27 02:21 UTC, merged